[package]
name = "rusttest_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.4.0"
serde_json = { version = "1.0.99", features = ["preserve_order"] }